- name: Create restore bucket
  hosts: 127.0.0.1
  vars_files:
    - ../vars.yml
    - ../../bridge/vars.yml
  tasks:
    - name: Drop bucket if exists
      ansible.builtin.uri:
        url: "http://{{server_public_ips[0]}}:8091/pools/default/buckets/default"
        method: DELETE
        force_basic_auth: true
        user: Administrator
        password: asdasd
      register: this
      failed_when: "this.status != 404 and this.status != 200"

    - name: Create bucket
      ansible.builtin.uri:
        url: "http://{{server_public_ips[0]}}:8091/pools/default/buckets"
        method: POST
        force_basic_auth: true
        user: Administrator
        password: asdasd
        body_format: form-urlencoded
        body:
          name: default
          ramQuota: "{{bucket_quota}}"
          storageBackend: "{{restore_storage_engine}}"
          evictionPolicy: "{{eviction_policy}}"
          numVBuckets: "{{bucket_vbs}}"
        status_code: 202
